import Head from 'next/head';
import { Container, Main, Title } from '../shared/styles/sharedstyles';

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>About</Title>
    </>
  );
}
