import Head from 'next/head';
import { Container, Main, Title } from '../shared/styles/sharedstyles';
import Cards from '../shared/styles/cards';

export default function Home() {
  return (
    <>
      <Head>
        <title>Main page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Hello World</Title>
    </>
  );
}
