import Head from 'next/head';
import { Title } from '../shared/styles/sharedstyles';
import { InferGetStaticPropsType } from 'next';
import CardList from '../Layouts/CardList/CardList';

interface IMovie {
  poster_path: string;
  adult: boolean;
  overview: string;
  release_date: string;
  genre_ids: number[];
  id: number;
  original_title: string;
  original_language: string;
  title: string;
  backdrop_path: string;
  popularity: number;
  vote_count: number;
  video: boolean;
  vote_average: number;
}

interface IMovies {
  page: number;
  results: IMovie[];
  total_results: number;
  total_pages: number;
}

const token =
  'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDZlZDk0MDBmYTE4OTFkN2RhODVhOTJlZTYwZjlhZCIsInN1YiI6IjYzOTI1OGE5ZDdmYmRhMDA4OGJiNzg2NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.LvYcmSE2-UhKt_QzeH7vIZGUd6_P8jZ93f17NPbZypE';

export const getStaticProps = async () => {
  const res = await fetch(
    'https://api.themoviedb.org/3/discover/movie?&page=1&sort_by=popularity.desc',
    {
      method: 'GET',
      headers: {
        accept: 'application/json',
        Authorization: `Bearer ${token}`,
      },
    }
  );

  const movies: IMovies = await res.json();

  return {
    props: {
      movies,
    },
  };
};

export default function Movies({ movies }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Movies</Title>
      <CardList movies={movies.results}/>
    </>
  );
}
