import Head from 'next/head';
import { Title } from '../shared/styles/sharedstyles';

export default function TVShows() {
  return (
    <>
      <Head>
        <title>TV Shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>TV Shows</Title>
    </>
  );
}
